import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

live_config_reload = true

[window]
startup_mode = "Maximized"
dynamic_padding = true
decorations = "none"
dynamic_title = true
opacity = 0.9

  [window.padding]
  x = 6
  y = 6

[scrolling]
history = 100_000
multiplier = 3

[font]
size = 20 # 35 # 18

  [font.normal]
  family = "mononoki Nerd Font"
  style = "Regular"

  [font.bold]
  family = "mononoki Nerd Font"
  style = "Bold"

  [font.italic]
  family = "mononoki Nerd Font"
  style = "Italic"

  [font.bold_italic]
  family = "FiraCode Nerd Font"
  style = "Bold Italic"

  [font.offset]
  x = 0
  y = 0

  [font.glyph_offset]
  x = 0
  y = 0
 
[bell]
animation = "EaseOutExpo"
duration = 0
color = "0xffffff"

[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"

[mouse]
hide_when_typing = false

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
save_to_clipboard = false

[cursor]
style = "Block"
unfocused_hollow = true

[[keyboard.bindings]]
key = "V"
mods = "Command"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Command"
action = "Copy"

[[keyboard.bindings]]
key = "Paste"
action = "Paste"

[[keyboard.bindings]]
key = "Copy"
action = "Copy"

[[keyboard.bindings]]
key = "H"
mods = "Command"
action = "Hide"

[[keyboard.bindings]]
key = "Q"
mods = "Command"
action = "Quit"
